-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 29, 2022 at 06:29 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 7.4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `movies`
--

-- --------------------------------------------------------

--
-- Table structure for table `film`
--

CREATE TABLE `film` (
  `id` int(11) NOT NULL,
  `judul` varchar(255) NOT NULL,
  `rating` varchar(255) NOT NULL,
  `sinopsis` varchar(255) NOT NULL,
  `deskripsi` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `negara` varchar(255) NOT NULL,
  `director` varchar(255) NOT NULL,
  `duration` varchar(255) NOT NULL,
  `studio` varchar(255) NOT NULL,
  `genre` varchar(255) NOT NULL,
  `actors` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `film`
--

INSERT INTO `film` (`id`, `judul`, `rating`, `sinopsis`, `deskripsi`, `image`, `negara`, `director`, `duration`, `studio`, `genre`, `actors`) VALUES
(107, 'Grease', '7', 'The Cat only grinned a little animal (she couldn\'t guess of what work it would be so proud as all that.\' \'With extras?\' asked the Gryphon, with a great thistle, to keep back the wandering hair that WOULD always get into her eyes; and once she remembered t', 'Qui quas in ipsa soluta quos quidem. Voluptatem ut sed animi expedita fugit. Vel ab dignissimos nulla omnis laborum. Laudantium et est aut inventore. Et deleniti qui ex ducimus sed voluptates qui. Dolore consequatur dicta corrupti. Enim beatae consequuntu', 'https://via.placeholder.com/640x480.png/00cc44?text=films+placeat', 'QA', 'Celine Sciamma', '19:22:42', 'Studio Canal', 'Documentary', 'Audrey Tautou'),
(108, 'Jurassic Park', '1', 'I\'ll tell you his history,\' As they walked off together. Alice laughed so much into the court, \'Bring me the list of singers. \'You may go,\' said the Hatter: \'but you could see it again, but it had fallen into it: there was not a bit hurt, and she at once ', 'Occaecati voluptatibus repellendus nesciunt repudiandae. Soluta voluptates culpa non dicta eum consequuntur odio. Saepe quia ut ducimus vel asperiores. Ex molestiae sint omnis ullam optio ullam.', 'https://via.placeholder.com/640x480.png/00eebb?text=films+quam', 'AS', 'Charles Chaplin', '22:31:57', 'Sony PictureS', 'Suspense', 'Sigourney Weaver'),
(109, 'North by Northwest', '4', 'Oh, I shouldn\'t want YOURS: I don\'t know,\' he went on talking: \'Dear, dear! How queer everything is queer to-day.\' Just then she walked on in the middle, nursing a baby; the cook had disappeared. \'Never mind!\' said the Mouse replied rather impatiently: \'a', 'Minus praesentium sit inventore doloribus enim. Consectetur repellat aut culpa quod neque neque. Sequi in omnis inventore odit quia quo. Commodi vero maxime officiis nobis quo qui. Quaerat praesentium odit minus autem quaerat. Alias hic nihil earum est. S', 'https://via.placeholder.com/640x480.png/00bb22?text=films+a', 'CA', 'Ang Lee', '20:16:47', 'Regency', 'Animation', 'Shelley Duvall'),
(110, 'Requiem for a Dream', '7', 'Alice,) and round the rosetree; for, you see, because some of them even when they liked, so that altogether, for the end of his great wig.\' The judge, by the carrier,\' she thought; \'and how funny it\'ll seem, sending presents to one\'s own feet! And how odd', 'Omnis rem eveniet quidem nemo molestiae aut nihil. Nobis veniam et odit unde incidunt expedita quod. Voluptatibus eum est et ullam sit nisi voluptatibus aut. Et quo et molestias quod.', 'https://via.placeholder.com/640x480.png/009955?text=films+nobis', 'CI', 'Charles Chaplin', '20:39:38', 'Studio Canal', 'Thriller', 'Amanda Plummer'),
(111, 'Panic Room', '6', 'This sounded promising, certainly: Alice turned and came back again. \'Keep your temper,\' said the Pigeon. \'I\'m NOT a serpent!\' said Alice in a moment. \'Let\'s go on till you come and join the dance. \'\"What matters it how far we go?\" his scaly friend replie', 'Tempore molestiae aut beatae dolorem incidunt assumenda tenetur. Corrupti tempore est necessitatibus molestiae maiores. Veniam debitis sit cumque provident nam. Eligendi ratione et eum voluptatem quam eaque. Quibusdam quod cupiditate iste accusantium aut.', 'https://via.placeholder.com/640x480.png/002288?text=films+tempora', 'DE', 'Jean-Pierre Melville', '22:26:39', 'Paramount', 'Action', 'Julia Roberts'),
(112, 'Ghostbusters', '3', 'Caterpillar. \'Is that the reason and all the jurymen on to the jury, and the party were placed along the sea-shore--\' \'Two lines!\' cried the Mouse, who seemed to have the experiment tried. \'Very true,\' said the Caterpillar. \'Is that the mouse doesn\'t get ', 'Voluptas non dolores est quibusdam dolorem. Quia est laboriosam quaerat optio sit ad. Nulla error odio et provident veniam ratione et. Quasi ut est recusandae similique alias. Reiciendis deleniti corrupti sint.', 'https://via.placeholder.com/640x480.png/00bbee?text=films+consequatur', 'SV', 'Alfred Hitchcock', '20:00:03', 'Miramax Films', 'Action', 'Diane Keaton'),
(113, 'Parasite', '8', 'I can\'t remember,\' said the Mock Turtle. \'And how do you know about this business?\' the King sharply. \'Do you know the song, \'I\'d have said to Alice, and she dropped it hastily, just in time to be seen: she found herself safe in a minute or two, which gav', 'Cum ut quos in voluptatibus. Hic et architecto voluptas dicta iusto. Aliquam nisi eius deleniti nulla. Rerum distinctio in qui nam enim aliquid. Aspernatur omnis fugiat autem debitis quisquam autem sed magnam. Ut odit quidem ducimus temporibus est eius. V', 'https://via.placeholder.com/640x480.png/006677?text=films+sit', 'AI', 'Alex Garland', '18:06:09', 'Focus Features', 'Comedy', 'Shelley Duvall'),
(114, 'The Departed', '4', 'Either the well was very nearly in the prisoner\'s handwriting?\' asked another of the house of the bottle was a general chorus of voices asked. \'Why, SHE, of course,\' said the King, looking round the neck of the lefthand bit of the gloves, and was going to', 'Ut est quo facilis. Facere qui veniam aspernatur ipsum molestiae recusandae nihil. Adipisci maiores aliquid necessitatibus esse autem minus dolor esse. Non at nihil rem debitis cupiditate placeat. Voluptatem numquam qui itaque nam eum quia.', 'https://via.placeholder.com/640x480.png/0099bb?text=films+rem', 'SZ', 'Patty Jenkins', '23:24:59', 'Warner Bros', 'Horror', 'Anne Hathaway'),
(115, 'The Lord of the Rings', '4', 'ME, and told me you had been jumping about like that!\' He got behind Alice as he fumbled over the edge with each hand. \'And now which is which?\' she said these words her foot as far as they came nearer, Alice could see, when she looked at Alice. \'It must ', 'Est repellendus odit dolor alias est doloribus. Consequuntur autem debitis culpa quos nostrum in. Deserunt sit repellendus quidem rerum facilis delectus. Et voluptas odio suscipit dolorem maiores earum.', 'https://via.placeholder.com/640x480.png/00ddff?text=films+sed', 'MR', 'Jim Jarmush', '21:17:57', 'UGC', 'Western', 'Gary Oldman'),
(116, 'The Watchmen', '8', 'King. (The jury all brightened up at this moment the King, the Queen, in a trembling voice, \'--and I hadn\'t cried so much!\' said Alice, (she had grown so large in the window?\' \'Sure, it\'s an arm, yer honour!\' (He pronounced it \'arrum.\') \'An arm, you goose', 'Architecto asperiores labore alias ut labore cumque qui. Iusto dolorem placeat odit libero earum ut impedit. Voluptas fugiat et consectetur libero consequatur optio. Aut nostrum repudiandae ut sit et eos accusantium. Doloremque quis deleniti ut ea libero.', 'https://via.placeholder.com/640x480.png/008888?text=films+laborum', 'TR', 'Akira Kurosawa', '22:01:09', 'Marvel Studios', 'TV Movie', 'Reese Witherspoon'),
(127, 'The Matrix', '6', 'I to do with you. Mind now!\' The poor little thing howled so, that he had to double themselves up and walking off to trouble myself about you: you must manage the best thing to get an opportunity of taking it away. She did not seem to encourage the witnes', 'Sunt sed enim facilis sunt. Dicta rerum et voluptate et quibusdam voluptatem nihil. Ratione voluptas non autem ut voluptatem.', 'https://via.placeholder.com/640x480.png/0022ee?text=films+inventore', 'MD', 'Nicole Garcia', '23:19:58', 'Fox Searchlight Pictures', 'War', 'Demi Moore'),
(128, 'The Sixth Sense', '4', 'I\'m better now--but I\'m a hatter.\' Here the Queen added to one of them bowed low. \'Would you tell me, Pat, what\'s that in the distance, and she hastily dried her eyes immediately met those of a tree a few minutes that she was out of the sort,\' said the Ca', 'Tenetur similique enim et laborum. Repellat quo et nemo ipsam. Odio aut voluptas sunt et molestiae inventore.', 'https://via.placeholder.com/640x480.png/00eeee?text=films+tempore', 'ZA', 'Xavier Dolan', '19:18:45', 'Gaumont', 'Fantasy', 'Christopher Walken'),
(129, 'L.A. Confidential', '9', 'I\'d been the right word) \'--but I shall remember it in a helpless sort of meaning in it.\' The jury all looked puzzled.) \'He must have a trial: For really this morning I\'ve nothing to do: once or twice she had to stop and untwist it. After a time she had p', 'Ea rerum aspernatur eligendi aut. Rerum sed non ut sunt velit est sint. Quo eum molestiae iste incidunt itaque delectus. Non cum qui accusamus impedit aspernatur.', 'https://via.placeholder.com/640x480.png/000066?text=films+quis', 'VG', 'Pedro Almodovar', '19:00:22', 'Blumhouse', 'Horror', 'Cate Blanchett'),
(130, 'Requiem for a Dream', '5', 'So Bill\'s got to come yet, please your Majesty!\' the soldiers did. After these came the royal children; there were no arches left, and all sorts of little birds and animals that had fallen into it: there were no tears. \'If you\'re going to do with you. Min', 'Incidunt excepturi architecto quis. Ad occaecati numquam rerum quia et numquam. Est eveniet id debitis sint. Ipsa optio impedit aperiam aliquid.', 'https://via.placeholder.com/640x480.png/004444?text=films+provident', 'TO', 'Jacques Audiard', '18:25:24', 'Warner Bros', 'Documentary', 'Felicity Jones'),
(131, 'Memento', '4', 'Alice said to the little door was shut again, and all dripping wet, cross, and uncomfortable. The first witness was the White Rabbit, \'but it doesn\'t understand English,\' thought Alice; \'I might as well go in ringlets at all; and I\'m sure she\'s the best w', 'Nostrum veritatis nemo numquam numquam omnis sunt. Consequatur distinctio officiis sunt sapiente officiis quam enim exercitationem. Ut voluptatem et laboriosam quis earum aut et.', 'https://via.placeholder.com/640x480.png/001177?text=films+laudantium', 'FM', 'Kathryn Bigelow', '21:51:15', 'TriStar', 'Music', 'Ingrid Bergman'),
(132, 'The Dark Knight', '8', 'I hadn\'t begun my tea--not above a week or so--and what with the Gryphon. \'I mean, what makes them bitter--and--and barley-sugar and such things that make children sweet-tempered. I only wish it was,\' said the Hatter: \'let\'s all move one place on.\' He mov', 'Ea temporibus quia voluptas nulla consequatur. Veniam impedit nostrum qui dolorem dolore aut. Saepe dicta ex accusantium veritatis et. Earum officiis id illo ducimus eos aut.', 'https://via.placeholder.com/640x480.png/0099ee?text=films+assumenda', 'ID', 'Christopher Nolan', '20:35:37', 'Paramount', 'Science Fiction', 'Angelina Jolie'),
(133, 'Silence', '4', 'And yet I wish you were me?\' \'Well, perhaps your feelings may be different,\' said Alice; \'but when you have to beat them off, and that if something wasn\'t done about it while the Dodo had paused as if she meant to take out of sight; and an old woman--but ', 'Tempora soluta illo molestias. Odio ipsa nostrum ipsam ipsa blanditiis dolores. Fugiat delectus quo consectetur placeat et natus. Iusto tempora ipsum necessitatibus ipsum.', 'https://via.placeholder.com/640x480.png/002200?text=films+nulla', 'IT', 'Luis Buñuel', '22:45:40', 'Syncopy', 'Drama', 'Mel Gibson'),
(134, 'The Girl with a Dragon Tatoo', '7', 'She had quite forgotten the words.\' So they couldn\'t see it?\' So she called softly after it, \'Mouse dear! Do come back in their proper places--ALL,\' he repeated with great curiosity. \'Soles and eels, of course,\' said the King, the Queen, who were all crow', 'Molestiae in et id. Saepe illo rerum voluptates quia. Dolores animi harum soluta rerum dolores pariatur rerum.', 'https://via.placeholder.com/640x480.png/008866?text=films+rerum', 'KY', 'François Ozon', '21:27:11', 'Legendary Pictures', 'Documentary', 'Joe Pesci'),
(135, 'Casino', '7', 'Bill, the Lizard) could not even get her head was so much already, that it signifies much,\' she said to herself, \'after such a thing as a last resource, she put it. She felt that this could not possibly reach it: she could not remember ever having seen in', 'Laboriosam assumenda ipsa dolorem perspiciatis molestiae illum officia saepe. Eos repudiandae est sit id. Sit inventore non labore animi nam enim qui. Nostrum illo aut nobis ex veniam repudiandae. Mollitia eum rerum et id et minus voluptatem. Qui voluptat', 'https://via.placeholder.com/640x480.png/007700?text=films+laudantium', 'ST', 'Victor Fleming', '21:45:11', 'Sony PictureS', 'TV Movie', 'Joaquin Phoenix'),
(136, 'Sicario', '3', 'Hatter; \'so I can\'t get out again. The Mock Turtle persisted. \'How COULD he turn them out of sight before the trial\'s begun.\' \'They\'re putting down their names,\' the Gryphon at the great concert given by the pope, was soon submitted to by all three dates ', 'Qui blanditiis exercitationem asperiores itaque ut. Provident dicta ratione animi sint quis maxime. Autem sit delectus vitae repellat numquam necessitatibus quo. Fugiat est magni accusamus ut impedit praesentium sit. Nihil nihil sapiente enim vero.', 'https://via.placeholder.com/640x480.png/00eeff?text=films+blanditiis', 'TR', 'Frank Capra', '22:56:17', 'American Zoetrope', 'Action', 'Jon Bernthal'),
(137, 'Warrior', '8', 'Alice could think of nothing else to do, and perhaps after all it might appear to others that what you would have appeared to them she heard it before,\' said Alice,) and round Alice, every now and then sat upon it.) \'I\'m glad I\'ve seen that done,\' thought', 'Enim delectus maiores quod sunt tempore. Et possimus explicabo qui. Nobis quae error fugiat. Rerum at est a nisi. Quibusdam architecto consectetur aut voluptatibus animi accusantium quas tempora.', 'https://via.placeholder.com/640x480.png/0044ff?text=films+omnis', 'CK', 'Milos Forman', '22:25:21', 'Blumhouse', 'Fantasy', 'Christian Bale'),
(138, 'Dune', '9', 'But if I\'m Mabel, I\'ll stay down here! It\'ll be no use their putting their heads downward! The Antipathies, I think--\' (for, you see, because some of YOUR adventures.\' \'I could tell you my adventures--beginning from this side of WHAT?\' thought Alice; \'I d', 'Dolores corporis ipsum accusamus perspiciatis quia tempore laudantium corporis. Quia voluptatem aliquid vero ut. Ut accusamus quam inventore. Earum voluptatibus sit temporibus.', 'https://via.placeholder.com/640x480.png/002233?text=films+reprehenderit', 'SI', 'Orson Welles', '21:04:36', 'New Line Cinema', 'Fantasy', 'Steve McQueen'),
(139, 'Raging Bull', '3', 'Dormouse; \'--well in.\' This answer so confused poor Alice, that she could not make out what it meant till now.\' \'If that\'s all I can do without lobsters, you know. Which shall sing?\' \'Oh, YOU sing,\' said the King. \'When did you call it purring, not growli', 'Aut quisquam voluptatem autem eaque. Quasi dolorum dolores excepturi optio. Nesciunt inventore incidunt voluptate enim quis laborum. Eaque sit sed fugit ut ea quos sed.', 'https://via.placeholder.com/640x480.png/001155?text=films+fugiat', 'CC', 'Uwe Boll', '22:19:06', 'Paramount', 'Mystery', 'Matthew McConaughey'),
(140, 'Terminator 2', '4', 'I\'d been the right size, that it would be very likely to eat or drink anything; so I\'ll just see what this bottle does. I do wonder what Latitude was, or Longitude either, but thought they were getting extremely small for a rabbit! I suppose you\'ll be tel', 'Nobis consequatur maiores et beatae deleniti. Ullam quidem possimus nobis quas occaecati totam est. Modi in explicabo consequatur qui.', 'https://via.placeholder.com/640x480.png/0033bb?text=films+deleniti', 'MD', 'Steve McQueen', '19:02:44', 'Warner Bros', 'Crime', 'Liv Tyler'),
(141, 'Persona', '3', 'By the time it vanished quite slowly, beginning with the strange creatures of her voice, and see what I get\" is the capital of Paris, and Paris is the same age as herself, to see how he did it,) he did with the Duchess, as she spoke--fancy CURTSEYING as y', 'Tempore harum sit ducimus quia ab. Labore sint qui libero et voluptas. Ipsum eos quaerat praesentium saepe.', 'https://via.placeholder.com/640x480.png/002299?text=films+est', 'KH', 'Nicolas Winding Refn', '23:19:29', 'Dreamworks', 'Animation', 'Dustin Hoffman'),
(142, 'Sicario', '3', 'I was sent for.\' \'You ought to go on. \'And so these three little sisters,\' the Dormouse said--\' the Hatter were having tea at it: a Dormouse was sitting on a three-legged stool in the house, \"Let us both go to on the shingle--will you come and join the.', 'Atque amet tempora velit nihil illum ut ut. Hic et praesentium perferendis modi voluptatem delectus. Et maxime ut aut veritatis sunt neque quas ratione. Saepe enim repellendus repellat et deserunt quas. Et dolorem et molestias aperiam et.', 'https://via.placeholder.com/640x480.png/0033cc?text=films+laudantium', 'KI', 'Michael Bay', '19:14:53', 'Paramount', 'Thriller', 'Sharon Stone'),
(143, 'Monty Python : Holy Grail', '8', 'That\'ll be a LITTLE larger, sir, if you could draw treacle out of a book,\' thought Alice \'without pictures or conversations in it, \'and what is the same height as herself; and when she was saying, and the whole pack rose up into a small passage, not much ', 'Nihil doloribus ut perferendis ea nulla labore. Molestias eveniet fugit eos enim recusandae blanditiis voluptas. Autem saepe pariatur impedit ut doloribus. Aut adipisci aut consequatur sed voluptas veniam eius. Inventore earum voluptate quia. Assumenda co', 'https://via.placeholder.com/640x480.png/006666?text=films+quis', 'BL', 'Dario Argento', '23:06:09', 'UGC', 'Biography', 'Cate Blanchett'),
(144, 'City of God', '8', 'Alice soon began talking again. \'Dinah\'ll miss me very much at this, but at the frontispiece if you hold it too long; and that in some alarm. This time Alice waited patiently until it chose to speak with. Alice waited a little, \'From the Queen. \'Their hea', 'Pariatur harum voluptas est ratione a. Fuga voluptatum quis eos delectus. Odit odit quibusdam ipsum vitae minus reiciendis. Qui aliquid non vel ut.', 'https://via.placeholder.com/640x480.png/00ff11?text=films+reprehenderit', 'PL', 'David Lean', '22:12:30', 'Paramount', 'War', 'Marlon Brando'),
(145, 'Casablanca', '4', 'And Alice was not an encouraging tone. Alice looked all round her, calling out in a very little! Besides, SHE\'S she, and I\'m sure I have to fly; and the jury asked. \'That I can\'t be Mabel, for I know is, it would like the three were all turning into littl', 'Nulla magni velit velit dicta ipsam accusamus dolorem. Et molestias nesciunt possimus blanditiis. Consequatur necessitatibus asperiores illo ut alias.', 'https://via.placeholder.com/640x480.png/0055ee?text=films+magnam', 'PS', 'Quentin Tarantino', '20:47:33', 'Weinstein Company', 'Romance', 'Samuel L.Jackson'),
(146, '2001 : A Space Odyssey', '7', 'Caterpillar. \'I\'m afraid I don\'t believe it,\' said the Cat, and vanished again. Alice waited patiently until it chose to speak good English); \'now I\'m opening out like the name: however, it only grinned when it grunted again, and looking at everything tha', 'Accusamus non asperiores consequuntur omnis adipisci ut. Perspiciatis minima quas eius praesentium dolorum autem. Neque quos placeat impedit laborum nihil aliquam.', 'https://via.placeholder.com/640x480.png/0011bb?text=films+hic', 'LR', 'Howard Hawks', '19:21:06', 'Weinstein Company', 'Music', 'Steve McQueen'),
(147, 'Ran', '5', 'CAN all that green stuff be?\' said Alice. \'Exactly so,\' said Alice. \'Nothing WHATEVER?\' persisted the King. \'When did you begin?\' The Hatter was the Rabbit asked. \'No, I give it up,\' Alice replied: \'what\'s the answer?\' \'I haven\'t opened it yet,\' said the ', 'Sapiente quia dolorum culpa minus qui ut. Doloribus sunt est et architecto aliquam et. Ut nostrum deserunt qui deleniti odit sunt. Voluptates minima ducimus dicta. Id veritatis quam blanditiis sit odit animi maiores. Possimus ratione illo enim illo laboru', 'https://via.placeholder.com/640x480.png/00ddff?text=films+consequuntur', 'PH', 'Bong Joon-ho', '23:42:16', 'Dreamworks', 'Mystery', 'Ellen Page'),
(148, 'Andreï Roublev', '9', 'King, \'and don\'t look at me like a telescope.\' And so she went on eagerly: \'There is such a thing before, but she was getting quite crowded with the next witness. It quite makes my forehead ache!\' Alice watched the Queen shrieked out. \'Behead that Dormous', 'Aut in sint provident adipisci sed. Temporibus incidunt qui sunt labore. Facere alias iste neque ex dolorem minima. Quisquam et ea officiis velit. Nemo fuga dignissimos maiores iusto deserunt est. Facilis qui sit ea unde.', 'https://via.placeholder.com/640x480.png/00dd77?text=films+alias', 'CL', 'Ava DuVernay', '18:30:12', 'Studio Canal', 'Thriller', 'Michelle Pfeiffer'),
(149, 'The Hateful Height', '8', 'As soon as it was very deep, or she should push the matter with it. There was nothing else to do, so Alice went timidly up to the Duchess: \'what a clear way you have to fly; and the poor animal\'s feelings. \'I quite forgot you didn\'t sign it,\' said the coo', 'Pariatur autem in molestias consequuntur ullam. Illo consequatur fugit eveniet sint consectetur asperiores quia quia. Totam voluptate dolor est vel sapiente sequi inventore.', 'https://via.placeholder.com/640x480.png/00ffee?text=films+et', 'GU', 'Marry Harron', '20:02:05', 'Regency', 'Family', 'Kim Basinger'),
(150, 'Carlito\'s Way', '4', 'King. \'Then it ought to go on. \'And so these three little sisters,\' the Dormouse denied nothing, being fast asleep. \'After that,\' continued the Gryphon. \'I\'ve forgotten the little golden key was lying on the slate. \'Herald, read the accusation!\' said the ', 'Optio eum est animi consequatur. Placeat et quia ex. Deserunt sint modi possimus. Voluptatem velit et temporibus consequuntur eaque autem. Corporis ullam blanditiis voluptatibus quo accusantium cum exercitationem. Unde et esse eos doloribus ut. Quisquam d', 'https://via.placeholder.com/640x480.png/00aaff?text=films+sed', 'KP', 'Pete Docter', '19:30:17', 'Fox 2000', 'Adventure', 'Frances McDormand'),
(151, 'Singing in the rain', '8', 'Alice kept her waiting!\' Alice felt a very difficult question. However, at last it sat down and cried. \'Come, there\'s no name signed at the March Hare. Visit either you like: they\'re both mad.\' \'But I don\'t want to go! Let me see: that would be a letter, ', 'Ea asperiores deleniti eius magnam vitae cum eius. Velit ut laboriosam recusandae. Iure quas est nihil magni. Ipsa saepe adipisci molestias praesentium totam suscipit vel. Reprehenderit ratione vitae iste veritatis ea sunt. Vero saepe nemo eius dolorem fu', 'https://via.placeholder.com/640x480.png/003333?text=films+sed', 'GP', 'Albert Dupontel', '19:40:48', 'UGC', 'Music', 'Bradley Cooper'),
(152, 'Monty Python : Holy Grail', '2', 'I\'ve finished.\' So they went up to the confused clamour of the room again, no wonder she felt sure it would not join the dance? \"You can really have no notion how long ago anything had happened.) So she stood still where she was quite surprised to see it ', 'Saepe libero facere labore dolor unde quia odio eaque. Aut aut eveniet rerum quia voluptas nisi et hic. Officia praesentium recusandae aut rerum commodi facere distinctio. Eos excepturi corporis aut non qui quia asperiores.', 'https://via.placeholder.com/640x480.png/008866?text=films+expedita', 'SR', 'Quentin Tarantino', '22:38:06', 'Syncopy', 'Romance', 'Steve Buscemi'),
(153, 'Your Name', '8', 'I dare say you\'re wondering why I don\'t want to see it written down: but I think it so yet,\' said the Mock Turtle would be the right distance--but then I wonder who will put on your head-- Do you think you could draw treacle out of the trees behind him. \'', 'Quo quasi et sunt nihil nostrum magni assumenda. Ab maiores ea eos quos. Iure voluptatem sed error similique qui rem eligendi. Ullam cumque rerum illum aut. Voluptatibus dicta et qui culpa odit. Nobis minus dolorem distinctio qui doloribus non rem deserun', 'https://via.placeholder.com/640x480.png/006633?text=films+distinctio', 'MF', 'Penny Marshall', '18:59:39', 'TriStar', 'Horror', 'Juliane Moore'),
(154, 'Andreï Roublev', '8', 'Go on!\' \'I\'m a poor man, your Majesty,\' said Two, in a solemn tone, \'For the Duchess. \'I make you a couple?\' \'You are all pardoned.\' \'Come, THAT\'S a good character, But said I could shut up like a serpent. She had not gone far before they saw Alice coming', 'Odio commodi corporis autem nisi eos omnis. Aspernatur voluptatem impedit perspiciatis nam natus. Odit praesentium quia alias nobis consequuntur inventore consequuntur. Nemo soluta et officiis est qui.', 'https://via.placeholder.com/640x480.png/0000ee?text=films+saepe', 'FI', 'Roberto Benigni', '19:27:48', 'Warner Bros', 'TV Movie', 'Liv Tyler'),
(155, 'Arrival', '9', 'Alice, quite forgetting in the sea!\' cried the Mock Turtle replied, counting off the mushroom, and crawled away in the wood, \'is to grow up again! Let me see: that would be very likely to eat her up in great disgust, and walked a little pattering of feet ', 'Numquam corporis distinctio optio optio labore. Ducimus est ipsa voluptatibus sed laudantium. Cum quam nemo alias. Hic rerum iure eius quibusdam aliquam. Velit quo deserunt magnam. Enim qui et corporis dolor ea. Aut quae libero assumenda rerum exercitatio', 'https://via.placeholder.com/640x480.png/007711?text=films+cupiditate', 'MW', 'Anne Fontaine', '18:31:55', 'Weinstein Company', 'TV Movie', 'Michelle Pfeiffer'),
(156, 'The Thing', '2', 'Gryphon went on in a rather offended tone, \'Hm! No accounting for tastes! Sing her \"Turtle Soup,\" will you, won\'t you, won\'t you, will you, won\'t you, won\'t you, will you, old fellow?\' The Mock Turtle said with some severity; \'it\'s very easy to take the p', 'Accusamus facere perferendis in ut molestiae dolorum. Perspiciatis inventore quasi nihil exercitationem repudiandae dolores.', 'https://via.placeholder.com/640x480.png/00ccff?text=films+quidem', 'DJ', 'M.Night Shyamalan', '19:25:59', 'Dreamworks', 'Fantasy', 'Marilyn Monroe'),
(157, 'The Dark Knight', '7', 'EVER happen in a shrill, passionate voice. \'Would YOU like cats if you want to be?\' it asked. \'Oh, I\'m not myself, you see.\' \'I don\'t see any wine,\' she remarked. \'It tells the day of the bill, \"French, music, AND WASHING--extra.\"\' \'You couldn\'t have want', 'Accusantium voluptatum vel tenetur sit veritatis exercitationem. Et porro impedit ducimus nihil nam laborum voluptas. Atque autem minima dolorem ut. Ut ipsum eum ut voluptatem.', 'https://via.placeholder.com/640x480.png/003300?text=films+eveniet', 'VU', 'Hayao Miyazaki', '18:43:26', 'Sony PictureS', 'Family', 'Jared Leto'),
(158, 'Whiplash', '6', 'England the nearer is to France-- Then turn not pale, beloved snail, but come and join the dance. Would not, could not, could not, would not join the dance?\"\' \'Thank you, it\'s a very respectful tone, but frowning and making faces at him as he spoke, and t', 'Quo voluptatem occaecati facilis accusamus quidem quis modi. Molestias qui sit dicta eum aut. Eum est totam voluptatem sequi odit reprehenderit quia. Sed ea vero ratione consequatur. Ut rem dolore omnis doloribus dolore dignissimos eos illum. Earum qui un', 'https://via.placeholder.com/640x480.png/007744?text=films+voluptas', 'TV', 'Sam Mendes', '20:28:11', 'Miramax Films', 'Science Fiction', 'Brie Larson'),
(159, 'Edward Cisorhands', '8', 'Classics master, though. He was an old Turtle--we used to say.\' \'So he did, so he did,\' said the Gryphon. \'It\'s all her riper years, the simple rules their friends had taught them: such as, that a red-hot poker will burn you if you could draw treacle out ', 'Esse consequatur neque et cumque repudiandae. Quo numquam ut sapiente odio consequatur soluta. Ut eum nobis voluptatem doloremque tempore occaecati et. Laborum vel similique qui voluptatem. Et impedit ratione fugit at. Id accusantium alias ut assumenda. Q', 'https://via.placeholder.com/640x480.png/009900?text=films+culpa', 'BH', 'Olivia Wilde', '21:28:46', 'New Line Cinema', 'Crime', 'Catherine Deneuve'),
(160, 'Rosemary\'s Baby', '8', 'I did: there\'s no use in waiting by the prisoner to--to somebody.\' \'It must be collected at once took up the little glass box that was sitting next to her. The Cat seemed to have him with them,\' the Mock Turtle. Alice was not quite know what it was quite ', 'Consequuntur quo omnis eaque voluptatem nihil blanditiis. Facere modi laudantium maxime aspernatur. Eveniet vero quia tenetur quas. Dolore est ad totam nihil quibusdam et dicta. Iure beatae accusantium temporibus veniam vitae. Et dolorum quo consequuntur ', 'https://via.placeholder.com/640x480.png/008844?text=films+eligendi', 'CO', 'Lilly Wachowski', '19:00:18', 'Pixar', 'Drama', 'Christoph Waltz'),
(161, 'Parasite', '3', 'Gryphon. \'I\'ve forgotten the Duchess replied, in a shrill, loud voice, and the pool rippling to the little creature down, and felt quite relieved to see its meaning. \'And just as if she were looking up into hers--she could hear the words:-- \'I speak sever', 'Quisquam in et id non iste aut. Consequatur sed assumenda excepturi consequatur. Quidem quia aliquam ipsa mollitia exercitationem. Beatae et eius dolore aut. Dicta doloremque reprehenderit a in molestias velit sunt. Consequatur qui quasi quod.', 'https://via.placeholder.com/640x480.png/002277?text=films+expedita', 'TG', 'Claire Denis', '22:04:32', 'Blumhouse', 'Thriller', 'Bill Murray'),
(162, '2001 : A Space Odyssey', '8', 'I do,\' said Alice sharply, for she had grown in the pool, and the baby joined):-- \'Wow! wow! wow!\' \'Here! you may stand down,\' continued the Gryphon. \'How the creatures wouldn\'t be in before the officer could get to the door, she ran off at once: one old ', 'Voluptatem deleniti asperiores sit. Quo alias in qui velit excepturi quod quidem. Voluptas quam nihil porro ut quisquam eveniet id. Ipsa molestias qui sed consequatur.', 'https://via.placeholder.com/640x480.png/008888?text=films+animi', 'GI', 'Luis Buñuel', '19:44:41', 'Gaumont', 'Mystery', 'Uma Thurman'),
(163, 'Singing in the rain', '7', 'Queen, who was peeping anxiously into its mouth and began picking them up again as she could, \'If you knew Time as well say,\' added the March Hare,) \'--it was at in all my life!\' She had quite a conversation of it had gone. \'Well! I\'ve often seen them at ', 'Vel voluptatibus impedit quidem iusto molestiae aut placeat. Aut iusto ea eaque quasi dolorem quas quisquam. Et sit accusantium ratione et. Velit expedita ut sit qui fugit eaque.', 'https://via.placeholder.com/640x480.png/00eeaa?text=films+corporis', 'BE', 'Sam Mendes', '20:45:07', 'Studio Canal', 'Action', 'Katheryn Winnick'),
(164, 'Carlito\'s Way', '1', 'Who for such dainties would not stoop? Soup of the house, quite forgetting in the chimney as she left her, leaning her head to keep back the wandering hair that WOULD always get into her eyes; and once she remembered how small she was going off into a con', 'Aut ut provident facilis atque ea. A totam et exercitationem consequatur voluptates. Odit cumque et ab dolorem. Neque tempore ullam ratione reiciendis aut exercitationem. Officiis aut sed voluptatem quidem ab vitae porro.', 'https://via.placeholder.com/640x480.png/009911?text=films+quidem', 'GE', 'Michael Mann', '19:24:00', '20th Century Fox', 'Romance', 'Javier Bardem'),
(165, '2001 : A Space Odyssey', '7', 'And certainly there was no use now,\' thought Alice, \'as all the children she knew that were of the baby, the shriek of the words \'EAT ME\' were beautifully marked in currants. \'Well, I\'ll eat it,\' said the Gryphon, half to itself, half to itself, \'Oh dear!', 'Quidem in explicabo quaerat sint quis. Occaecati reprehenderit nihil sint et. Accusamus et ut perspiciatis neque. Ipsum ut et consequatur est suscipit qui qui.', 'https://via.placeholder.com/640x480.png/004488?text=films+provident', 'AZ', 'Robert Wise', '21:00:04', 'Marvel Studios', 'Animation', 'Clive Owen'),
(166, 'Carrie', '9', 'The only things in the court!\' and the little golden key and hurried off to the little golden key was lying under the sea--\' (\'I haven\'t,\' said Alice)--\'and perhaps you were all ornamented with hearts. Next came an angry tone, \'Why, Mary Ann, and be turne', 'Iure eum repellat deserunt ut eligendi. Omnis id at praesentium odit. Ad dolor impedit rerum et dicta quia nihil ut. Harum similique eaque odit qui occaecati vero.', 'https://via.placeholder.com/640x480.png/009999?text=films+commodi', 'VG', 'John McTiernan', '23:16:24', 'UGC', 'Action', 'Sandra Bullock'),
(167, 'The Artist', '5', 'Alice. \'I don\'t know the meaning of it in less than a rat-hole: she knelt down and began bowing to the fifth bend, I think?\' he said to the door. \'Call the next verse,\' the Gryphon remarked: \'because they lessen from day to day.\' This was such a noise ins', 'Architecto omnis et omnis nam fugiat. Necessitatibus nulla tenetur excepturi dolor. Adipisci eos odit sed qui minus. Neque assumenda ratione nesciunt.', 'https://via.placeholder.com/640x480.png/005555?text=films+soluta', 'LB', 'Park Chan-Wook', '21:14:35', 'TriStar', 'Western', 'Andrew Garfield'),
(168, 'Star Wars', '4', 'Imagine her surprise, when the White Rabbit interrupted: \'UNimportant, your Majesty means, of course,\' the Mock Turtle; \'but it sounds uncommon nonsense.\' Alice said very humbly; \'I won\'t have any rules in particular; at least, if there are, nobody attend', 'Quos non commodi et et sunt et. Neque quam nesciunt est suscipit voluptatem qui. Et aut minima non consequatur quia quia. Voluptas et modi iste sit modi nobis.', 'https://via.placeholder.com/640x480.png/009977?text=films+et', 'UY', 'Lois Weber', '18:46:16', 'Legendary Pictures', 'Suspense', 'Adam Driver'),
(169, 'Stand by Me', '3', 'Alice went on in a day did you call it sad?\' And she squeezed herself up and beg for its dinner, and all the rats and--oh dear!\' cried Alice, with a kind of authority among them, called out, \'First witness!\' The first thing I\'ve got to grow here,\' said th', 'Temporibus est ut cumque repellendus blanditiis eius vitae qui. Velit necessitatibus omnis assumenda neque necessitatibus. Non itaque culpa hic nisi ab. Optio velit aut quia eaque.', 'https://via.placeholder.com/640x480.png/00ff99?text=films+dolor', 'BN', 'Fritz Lang', '19:43:02', 'TriStar', 'War', 'Michael Shannon'),
(170, 'Inception', '8', 'Alice herself, and began to say a word, but slowly followed her back to my jaw, Has lasted the rest of the garden: the roses growing on it but tea. \'I don\'t like the look of the trees had a little timidly, \'why you are painting those roses?\' Five and Seve', 'Quibusdam commodi et sed qui saepe eum hic. Quidem tenetur asperiores non magnam ullam consequatur voluptates. Temporibus qui aut veniam optio voluptas. Asperiores ut temporibus soluta voluptas. Recusandae facere magnam magnam quam. Hic esse soluta quia e', 'https://via.placeholder.com/640x480.png/0055dd?text=films+voluptatum', 'GR', 'Milos Forman', '18:20:18', 'Miramax Films', 'Music', 'Sigourney Weaver'),
(171, 'Toy Story', '8', 'Wonderland, though she felt that it had finished this short speech, they all cheered. Alice thought the poor little thing was snorting like a writing-desk?\' \'Come, we shall have some fun now!\' thought Alice. \'I\'m a--I\'m a--\' \'Well! WHAT are you?\' said Ali', 'Commodi commodi rerum molestiae consectetur sint. Nihil et dolores doloribus magni sequi. Nemo et delectus ut omnis ea consequatur.', 'https://via.placeholder.com/640x480.png/001100?text=films+quo', 'TM', 'Paul Thomas Anderson', '23:13:41', 'TriStar', 'Drama', 'Hugh Jackman'),
(172, 'Monty Python : Holy Grail', '4', 'Hatter, \'when the Queen said to Alice, and she thought at first was moderate. But the snail replied \"Too far, too far!\" and gave a sudden burst of tears, \'I do wish they WOULD not remember ever having seen such a hurry that she had drunk half the bottle, ', 'Consequatur similique odit vel nobis maiores. Tempore fuga qui ab non in quia. Aut ea illo facere qui at earum iusto reprehenderit. Explicabo animi eligendi tempore et et.', 'https://via.placeholder.com/640x480.png/0033dd?text=films+necessitatibus', 'GW', 'Nicolas Winding Refn', '21:17:52', 'Lionsgate', 'Crime', 'Al Pacino'),
(173, 'V for Vendetta', '9', 'I THINK I can find it.\' And she thought of herself, \'I wish I hadn\'t mentioned Dinah!\' she said to the Mock Turtle to sing \"Twinkle, twinkle, little bat! How I wonder who will put on his slate with one eye; but to get in at the flowers and the Queen, \'and', 'Autem consequatur sed quis sit. Quae quia fugit ut temporibus. Sed iste optio sed qui officia omnis sed aut. Omnis nihil totam animi ut similique earum. Est voluptatem et nulla atque qui est. Non aperiam voluptate error non id.', 'https://via.placeholder.com/640x480.png/00ddcc?text=films+et', 'GS', 'Jennifer Kent', '20:13:42', 'Lucasfilm', 'Suspense', 'Matthew McConaughey'),
(174, 'Kill Bill Vol.1', '8', 'Caterpillar took the thimble, looking as solemn as she spoke--fancy CURTSEYING as you\'re falling through the air! Do you think you\'re changed, do you?\' \'I\'m afraid I am, sir,\' said Alice; \'but a grin without a grin,\' thought Alice; \'I daresay it\'s a set o', 'Dolorem eveniet blanditiis cum sit suscipit nobis. Et harum quia dolorem eum. Reprehenderit aut dolorum atque dicta maiores animi fugit. Magni et optio fugiat aliquid pariatur voluptate.', 'https://via.placeholder.com/640x480.png/008833?text=films+sint', 'RS', 'Xavier Dolan', '20:30:18', 'Miramax Films', 'Fantasy', 'Carrie Fisher'),
(175, 'Alien', '1', 'Beautiful, beautiful Soup!\' CHAPTER XI. Who Stole the Tarts? The King looked anxiously at the great concert given by the whole pack of cards!\' At this moment Five, who had followed him into the loveliest garden you ever see you any more!\' And here poor Al', 'Veritatis veritatis iusto amet soluta facilis molestiae dolore. Pariatur nobis explicabo doloremque. Accusamus quis vel et ipsum. Quaerat libero repudiandae architecto cum.', 'https://via.placeholder.com/640x480.png/00aabb?text=films+quia', 'UA', 'Andrea Arnold', '20:35:39', 'Paramount', 'TV Movie', 'Johnny Depp'),
(176, 'Monty Python : Holy Grail', '7', 'Alice was beginning to see what this bottle was NOT marked \'poison,\' so Alice went timidly up to Alice, and her face like the three gardeners who were giving it a very truthful child; \'but little girls of her sharp little chin into Alice\'s shoulder as she', 'Tenetur voluptatem tempora id incidunt explicabo nostrum vel modi. Est ex et dolorum commodi sint sit quis. Omnis nisi qui id ut eum blanditiis. Recusandae temporibus repellendus itaque autem. Excepturi quia laboriosam itaque aut maxime odio fugit expedit', 'https://via.placeholder.com/640x480.png/0066dd?text=films+consequatur', 'UA', 'Spike Jonze', '19:03:40', 'Fox 2000', 'Animation', 'Russell Crowe'),
(177, 'American Beauty', '2', 'King. \'Shan\'t,\' said the Mock Turtle, who looked at Alice. \'It must have imitated somebody else\'s hand,\' said the Caterpillar decidedly, and there she saw maps and pictures hung upon pegs. She took down a good opportunity for repeating his remark, with va', 'Nobis dolores doloribus accusamus totam sit illum rem sapiente. Commodi odio maiores reprehenderit. Doloribus iure neque omnis similique alias. Minus totam hic maiores tempore. Eveniet et impedit consequatur dicta. Cupiditate nulla beatae aliquid mollitia', 'https://via.placeholder.com/640x480.png/00ddaa?text=films+quos', 'HK', 'David Fincher', '18:18:20', 'Dreamworks', 'Comedy', 'Gene Kelly'),
(178, 'Psycho', '2', 'The first witness was the Duchess\'s cook. She carried the pepper-box in her face, with such sudden violence that Alice said; but was dreadfully puzzled by the fire, and at last turned sulky, and would only say, \'I am older than you, and must know better\';', 'Atque dolorem fugit nobis incidunt aut ratione. Officiis qui dolorem possimus. Quo repellat qui placeat repudiandae. Et illo quod quisquam est non.', 'https://via.placeholder.com/640x480.png/0066ff?text=films+explicabo', 'IL', 'Pete Docter', '18:51:04', 'Sony PictureS', 'Biography', 'Jim Carrey'),
(179, 'Jurassic Park', '2', 'I have to fly; and the game was in a sulky tone; \'Seven jogged my elbow.\' On which Seven looked up and rubbed its eyes: then it watched the Queen shrieked out. \'Behead that Dormouse! Turn that Dormouse out of sight: \'but it doesn\'t mind.\' The table was a ', 'Dolores optio quia repellat quia. Non corrupti quasi fugiat ea. Voluptatem rerum fugiat repudiandae asperiores autem. Repellat hic possimus rem rerum. Id quaerat enim unde veritatis provident qui. Eligendi sunt facilis ipsam nihil. Quis tempore enim adipi', 'https://via.placeholder.com/640x480.png/00ff22?text=films+rem', 'AO', 'Danny Boyle', '18:59:37', 'Columbia Pictures', 'Adventure', 'Ingrid Bergman'),
(180, 'Trainspotting', '3', 'So you see, Alice had never heard of such a tiny golden key, and unlocking the door began sneezing all at once. The Dormouse shook its head to feel very queer indeed:-- \'\'Tis the voice of the Gryphon, \'that they WOULD go with Edgar Atheling to meet Willia', 'Tempora nostrum quia culpa voluptate id iure. Eum et enim sit ex nesciunt. Qui facilis cum magni facere. Minus impedit ea ea voluptatibus. Eos similique aut doloribus ea. Aperiam alias quis eum vitae cumque. Alias velit dignissimos unde et quo est.', 'https://via.placeholder.com/640x480.png/0011ff?text=films+non', 'MQ', 'Alex Garland', '19:34:53', 'Pixar', 'Romance', 'Scarlett Johanson'),
(181, 'The Irishman', '2', 'She said the Caterpillar. Alice thought this must ever be A secret, kept from all the jurymen on to her chin upon Alice\'s shoulder, and it sat down with her face in some alarm. This time there were a Duck and a Dodo, a Lory and an old woman--but then--alw', 'Amet sit quia quidem rerum deleniti amet. Esse aut repellendus doloribus eaque quod. Minus at labore perspiciatis doloribus. Placeat omnis voluptas ducimus aut. Quia facilis dolorum architecto labore.', 'https://via.placeholder.com/640x480.png/003377?text=films+cupiditate', 'IS', 'Lulu Wang', '19:17:18', 'TriStar', 'Crime', 'Russell Crowe'),
(182, 'Winter Sleep', '6', 'Alice; \'I might as well go back, and see what was on the top of her head struck against the ceiling, and had been for some minutes. Alice thought she might find another key on it, and burning with curiosity, she ran off at once: one old Magpie began wrapp', 'Dolor soluta id reiciendis. Quibusdam qui voluptas qui. Libero est ducimus non in est et et. Deleniti aliquid omnis asperiores enim hic. Rerum velit impedit et veritatis sunt doloremque. Sit consequatur est esse placeat et aut eum. Dolorem tenetur volupta', 'https://via.placeholder.com/640x480.png/00ff99?text=films+ut', 'GR', 'Jim Jarmush', '22:12:58', 'Gaumont', 'Biography', 'Kurt Russel'),
(183, 'Suspiria', '5', 'Queen, in a deep voice, \'are done with a teacup in one hand, and a pair of gloves and the other ladder?--Why, I hadn\'t mentioned Dinah!\' she said to herself how this same little sister of hers would, in the night? Let me see: that would be grand, certainl', 'Quam modi veniam deserunt maiores fugiat sunt. Vero eum laudantium consectetur porro ea laboriosam asperiores. Excepturi molestiae non minus sed.', 'https://via.placeholder.com/640x480.png/0088bb?text=films+cum', 'PS', 'John Woo', '19:01:42', 'Marvel Studios', 'TV Movie', 'Kim Novak'),
(184, 'Monty Python : Holy Grail', '7', 'I must go and get in at the thought that it was too late to wish that! She went on again:-- \'You may not have lived much under the window, and on it in asking riddles that have no idea what a Gryphon is, look at it!\' This speech caused a remarkable sensat', 'Omnis repellendus rerum consequatur reprehenderit quaerat eum voluptatem dignissimos. Eaque est sit occaecati aut sunt et veniam minus. Ut ut autem similique temporibus eaque natus. Sit sed beatae sed officia eum suscipit.', 'https://via.placeholder.com/640x480.png/0077bb?text=films+sapiente', 'LB', 'Kathryn Bigelow', '19:47:06', 'Legendary Pictures', 'TV Movie', 'Lauren Cohan'),
(185, 'The Dark Knight', '1', 'While she was losing her temper. \'Are you content now?\' said the last concert!\' on which the March Hare, who had not got into the way I want to go! Let me see: I\'ll give them a railway station.) However, she got to come upon them THIS size: why, I should ', 'Veniam cupiditate provident quaerat iste at ducimus. Sit nam qui quis reiciendis molestiae ratione quos. Quasi quia officiis assumenda magnam in ipsum.', 'https://via.placeholder.com/640x480.png/00dd66?text=films+alias', 'BY', 'Luchino Visconti', '23:32:59', 'Regency', 'Comedy', 'Michael Caine'),
(186, 'Inside Out', '2', 'Lory, as soon as there seemed to be patted on the breeze that followed them, the melancholy words:-- \'Soo--oop of the officers of the baby?\' said the Footman. \'That\'s the first question, you know.\' \'I DON\'T know,\' said Alice as he could go. Alice took up ', 'Nulla temporibus repudiandae dolorum ut ut. Perferendis perspiciatis et eligendi excepturi. Aperiam aspernatur quia ducimus molestiae aut. Vel fuga placeat deleniti mollitia sequi. Non omnis officiis tempore ab. Blanditiis itaque facilis maxime dignissimo', 'https://via.placeholder.com/640x480.png/0011ff?text=films+voluptatem', 'TT', 'David O.Russel', '21:35:11', 'Blumhouse', 'Family', 'Sandra Bullock'),
(187, 'Kill Bill', '2', 'Dinah, and saying \"Come up again, dear!\" I shall ever see such a rule at processions; \'and besides, what would be like, but it makes me grow smaller, I can kick a little!\' She drew her foot as far down the chimney, has he?\' said Alice in a voice outside, ', 'Voluptatem laboriosam blanditiis quia maxime. Excepturi vel labore laudantium neque et. Dolorem et ipsam veniam molestiae. Debitis iusto temporibus molestiae. Minus totam alias omnis dolore. Repellendus non dolores est occaecati. Consequuntur accusantium ', 'https://via.placeholder.com/640x480.png/000055?text=films+recusandae', 'EE', 'Xavier Dolan', '22:02:36', 'Columbia Pictures', 'Fantasy', 'Robin Williams'),
(188, 'Inside Out', '3', 'I\'ll tell you my adventures--beginning from this side of the busy farm-yard--while the lowing of the March Hare will be the right size for going through the door, and the whole cause, and condemn you to leave the court; but on second thoughts she decided ', 'Soluta sunt autem quibusdam placeat et vero. Maiores ad iure unde. Cumque nemo dolore ipsam et eum. Consequuntur dignissimos in molestiae laudantium et itaque. Illum qui ut iste inventore accusantium animi. Perferendis vel nemo eos eum provident.', 'https://via.placeholder.com/640x480.png/00ccee?text=films+et', 'HT', 'Alfred Hitchcock', '21:39:56', 'Lionsgate', 'Crime', 'Felicity Jones'),
(189, 'Ran', '5', 'ONE respectable person!\' Soon her eye fell on a crimson velvet cushion; and, last of all this grand procession, came THE KING AND QUEEN OF HEARTS. Alice was only a child!\' The Queen turned angrily away from him, and very neatly and simply arranged; the on', 'Soluta cum molestias ad ab pariatur. Ut dolorum aliquam est eos saepe mollitia ex. Et eveniet aliquam beatae rem debitis. Exercitationem inventore sequi enim expedita perspiciatis aliquid.', 'https://via.placeholder.com/640x480.png/009922?text=films+praesentium', 'CR', 'Michel Audiard', '18:54:34', 'Lucasfilm', 'Science Fiction', 'Léa Seydoux'),
(190, 'Catch me if you can', '1', 'THAT direction,\' the Cat in a very pretty dance,\' said Alice desperately: \'he\'s perfectly idiotic!\' And she went on, \'if you don\'t explain it as to size,\' Alice hastily replied; \'only one doesn\'t like changing so often, of course was, how to begin.\' For, ', 'Est dolorum et minus est temporibus doloribus eaque. Ut necessitatibus quis aut modi. Nulla ex amet animi voluptatem qui. Doloribus est autem praesentium temporibus fugiat. Magnam incidunt alias modi alias voluptatem ipsum.', 'https://via.placeholder.com/640x480.png/003311?text=films+sed', 'EH', 'Bong Joon-ho', '20:15:17', 'Miramax Films', 'Comedy', 'Kim Basinger'),
(191, 'Apocalypse Now', '9', 'Alice noticed, had powdered hair that curled all over with fright. \'Oh, I beg your pardon!\' cried Alice again, for she was always ready to agree to everything that Alice quite hungry to look through into the way I ought to have no idea what Latitude or Lo', 'Voluptatem quod architecto laborum et. Qui nulla consequatur deserunt officiis. Quibusdam magni dolor exercitationem expedita.', 'https://via.placeholder.com/640x480.png/0099bb?text=films+nesciunt', 'SV', 'John McTiernan', '22:30:22', 'New Line Cinema', 'Suspense', 'Amy Adams'),
(192, 'Platoon', '9', 'I am very tired of being such a tiny little thing!\' It did so indeed, and much sooner than she had found the fan and a pair of gloves and a Canary called out in a great crash, as if he would not join the dance? Will you, won\'t you, will you, won\'t you, wo', 'Qui est molestiae eaque aut. Ea velit autem nesciunt sed ullam. Tenetur hic soluta fuga dicta consequuntur qui. Eveniet est consequatur pariatur tenetur praesentium repellat.', 'https://via.placeholder.com/640x480.png/002222?text=films+voluptatem', 'VU', 'Ingmar Bergman', '19:54:06', 'Fox Searchlight Pictures', 'Horror', 'Bradley Cooper'),
(193, 'Kill Bill Vol.2', '4', 'I am, sir,\' said Alice; \'living at the mouth with strings: into this they slipped the guinea-pig, head first, and then, \'we went to work shaking him and punching him in the sea. But they HAVE their tails in their proper places--ALL,\' he repeated with grea', 'Repellendus sit quia dolor doloribus magni sit. Aspernatur nulla dolor nostrum asperiores. Asperiores inventore explicabo ipsa amet dolores et quae. Dicta ratione totam et. In velit alias suscipit tempore at. Ut aut provident ea.', 'https://via.placeholder.com/640x480.png/006666?text=films+ipsa', 'KM', 'Nadine Labaki', '21:07:59', 'Warner Bros', 'Romance', 'Naomi Watts');
INSERT INTO `film` (`id`, `judul`, `rating`, `sinopsis`, `deskripsi`, `image`, `negara`, `director`, `duration`, `studio`, `genre`, `actors`) VALUES
(194, 'Shutter Island', '5', 'Gryphon only answered \'Come on!\' cried the Mouse, turning to Alice an excellent plan, no doubt, and very soon had to stop and untwist it. After a while she was about a thousand times as large as the rest of the Mock Turtle went on. \'Or would you like to s', 'Sunt exercitationem aspernatur et expedita temporibus laudantium ipsa. Aliquid ratione dolorem similique aut quos voluptatibus. Repellendus repellendus ullam adipisci quo. Voluptatem nulla esse quas.', 'https://via.placeholder.com/640x480.png/003333?text=films+soluta', 'NP', 'Pedro Almodovar', '23:02:33', 'Gaumont', 'Romance', 'Emily Blunt'),
(195, 'The Lion King', '5', 'Alice was very likely true.) Down, down, down. Would the fall was over. Alice was just possible it had grown up,\' she said this, she came upon a neat little house, and have next to her. \'I wish I hadn\'t cried so much!\' said Alice, very loudly and decidedl', 'Expedita eum eos cum hic repudiandae non harum laudantium. Aut est culpa aut dicta harum alias neque est. Molestias voluptas exercitationem et aut cumque quis repudiandae.', 'https://via.placeholder.com/640x480.png/00ddee?text=films+nam', 'GG', 'Steve McQueen', '18:49:08', 'UGC', 'War', 'Natalie Portman'),
(196, 'Hacksaw Ridge', '1', 'For some minutes it puffed away without speaking, but at the moment, \'My dear! I shall be a person of authority over Alice. \'Stand up and repeat something now. Tell her to begin.\' For, you see, as they all crowded together at one end of the Gryphon, and t', 'Ad eos incidunt et maiores aut. Eos consequuntur provident inventore. Vitae quo architecto et dolore enim iure sint. Et aut in at perspiciatis dolores. Voluptatem et voluptatem ipsum enim quia vitae. Cumque aut voluptatibus omnis quis at suscipit. Qui duc', 'https://via.placeholder.com/640x480.png/000055?text=films+qui', 'SZ', 'Frank Capra', '19:17:33', 'Studio Canal', 'Animation', 'Annie Girardot'),
(197, 'Parasite', '7', 'Laughing and Grief, they used to come upon them THIS size: why, I should frighten them out of its little eyes, but it is.\' \'I quite forgot how to begin.\' For, you see, as well as she swam lazily about in a great hurry. An enormous puppy was looking about ', 'Ut et mollitia et nemo rerum. Atque et quo sunt. Ea necessitatibus impedit accusamus amet ipsam quam. Delectus non atque aliquid expedita aut modi.', 'https://via.placeholder.com/640x480.png/0022dd?text=films+voluptatem', 'SI', 'Marguerite Duras', '21:21:45', 'Studio Canal', 'Suspense', 'Tim Roth'),
(198, 'Cotton Club', '7', 'Alice said to herself as she went on. \'Would you tell me,\' said Alice, \'it\'s very interesting. I never knew so much into the earth. Let me see: four times seven is--oh dear! I shall fall right THROUGH the earth! How funny it\'ll seem, sending presents to o', 'Fugit enim omnis et. Maxime quisquam odio accusantium quasi non non accusamus odit. Blanditiis nihil saepe aut maxime molestias qui. Ut unde suscipit molestiae eaque repellendus esse.', 'https://via.placeholder.com/640x480.png/00ee55?text=films+omnis', 'TD', 'Damien Chazelle', '21:39:06', 'Dreamworks', 'Horror', 'Colin Firth'),
(199, 'Forrest Gump', '7', 'Caterpillar took the regular course.\' \'What was THAT like?\' said Alice. \'Well, then,\' the Gryphon hastily. \'Go on with the name of nearly everything there. \'That\'s the judge,\' she said this last remark. \'Of course you know what \"it\" means.\' \'I know SOMETH', 'Autem ea molestiae architecto doloremque. Ab perferendis nisi eaque vitae voluptas est in. Rem praesentium nostrum libero explicabo facere.', 'https://via.placeholder.com/640x480.png/001133?text=films+amet', 'BH', 'Sergio Leone', '23:27:12', 'Fox 2000', 'Documentary', 'Jonah Hill'),
(200, 'Room', '2', 'I will prosecute YOU.--Come, I\'ll take no denial; We must have a trial: For really this morning I\'ve nothing to do: once or twice she had found her way out. \'I shall be late!\' (when she thought it would,\' said the Mock Turtle Soup is made from,\' said the ', 'Molestiae ad explicabo quasi qui sit. Maxime eos est necessitatibus quo. Molestias at nisi aut in. Accusamus reprehenderit natus perspiciatis eveniet. Aliquid commodi ut fugiat libero ut quis. Quo itaque eum et. Totam ab nihil aut reprehenderit aut odit c', 'https://via.placeholder.com/640x480.png/003300?text=films+et', 'HU', 'Jennifer Kent', '19:35:14', 'Fox 2000', 'Western', 'Michael Madsen'),
(201, 'L.A. Confidential', '1', 'Gryphon. \'It\'s all about for it, he was speaking, so that they couldn\'t get them out with trying, the poor child, \'for I can\'t put it more clearly,\' Alice replied thoughtfully. \'They have their tails in their paws. \'And how do you know about it, so she sa', 'Laborum cum autem quisquam autem tempore consequatur. Omnis quia quo qui commodi qui. Perferendis officiis quibusdam et qui possimus magnam eos qui. Alias temporibus error voluptates sit. In maxime vitae repudiandae debitis ipsum consectetur.', 'https://via.placeholder.com/640x480.png/00eeee?text=films+quia', 'NI', 'James Cameron', '21:21:42', 'Weinstein Company', 'Comedy', 'Michael Shannon'),
(202, 'The Lobster', '1', 'So she was coming back to the Mock Turtle, and said \'No, never\') \'--so you can have no sort of knot, and then raised himself upon tiptoe, put his mouth close to her great delight it fitted! Alice opened the door with his whiskers!\' For some minutes the wh', 'Modi sint neque sapiente dolores voluptatem. Vero eos minima quasi unde impedit eius. Odit optio impedit distinctio molestiae. Ea autem pariatur voluptatem ut aspernatur quo. Quidem ut ratione excepturi voluptas. Quia blanditiis quasi rerum atque eos volu', 'https://via.placeholder.com/640x480.png/007711?text=films+dignissimos', 'BE', 'Clint Eastwood', '18:12:24', 'UGC', 'Animation', 'Jane Fonda'),
(203, 'A Beautiful Mind', '8', 'Alice called out \'The Queen! The Queen!\' and the other side of the trees upon her arm, with its head, it WOULD twist itself round and round Alice, every now and then, if I shall have to fly; and the sounds will take care of the day; and this was his first', 'Quo possimus nisi rem fugiat a. Officia recusandae nihil qui dolor sequi expedita. Quidem labore necessitatibus ut fuga ipsa. Vitae sunt tempora blanditiis. Enim architecto magnam atque voluptates qui. Saepe suscipit et et nihil. Temporibus ducimus labore', 'https://via.placeholder.com/640x480.png/007744?text=films+illo', 'FM', 'Lana Wachowski', '23:27:12', 'Legendary Pictures', 'Drama', 'Mila Kunis'),
(204, 'The Sixth Sense', '6', 'I\'ve offended it again!\' For the Mouse was swimming away from her as hard as it happens; and if the Queen shouted at the corners: next the ten courtiers; these were ornamented all over with William the Conqueror.\' (For, with all speed back to them, and co', 'Iusto dolores quis saepe earum facere. Temporibus ut accusantium hic illo dolorum. Labore aut est quaerat consequatur sapiente qui eligendi vel.', 'https://via.placeholder.com/640x480.png/000000?text=films+natus', 'SI', 'Robert Altman', '20:34:51', 'Universal Pictures', 'Western', 'Jennifer Aniston'),
(205, '300', '6', 'Dormouse\'s place, and Alice was thoroughly puzzled. \'Does the boots and shoes!\' she repeated in a low voice. \'Not at first, perhaps,\' said the Lory hastily. \'I thought it would,\' said the Queen, in a whisper, half afraid that she tipped over the fire, sti', 'Est omnis cupiditate perferendis laudantium cum sed. Aut aut voluptate doloribus tempora. Qui qui doloremque voluptatem officiis maiores vel. Sequi ea eveniet nihil aut eum.', 'https://via.placeholder.com/640x480.png/000022?text=films+id', 'SY', 'James Wan', '22:35:34', 'Bad Robot', 'Comedy', 'Rachel Weisz'),
(206, 'Citizen Kane', '3', 'It was as much as she tucked her arm affectionately into Alice\'s, and they lived at the house, and the Queen, \'and take this child away with me,\' thought Alice, \'they\'re sure to happen,\' she said to the door, she found she had this fit) An obstacle that c', 'Debitis fugit non quam aut enim reprehenderit laudantium. Eum quod et officia. Saepe tenetur et et dolorem at mollitia ipsa. Ut autem consequatur modi reprehenderit modi. Ex at saepe aperiam voluptatem. Ut consequatur voluptas aut.', 'https://via.placeholder.com/640x480.png/000033?text=films+ullam', 'AD', 'Sam Mendes', '23:01:33', 'Regency', 'Biography', 'Jonah Hill'),
(207, 'Lawrence of Arabie', '3', 'CHORUS. (In which the cook was busily stirring the soup, and seemed to listen, the whole party look so grave that she ought to go nearer till she too began dreaming after a minute or two, which gave the Pigeon went on, \'you see, a dog growls when it\'s ple', 'Fuga repudiandae esse iure voluptatem voluptatem aliquid. Ducimus qui temporibus porro itaque. Ipsa dolorem nesciunt consequuntur dolor alias ratione labore nihil. Eum voluptatibus explicabo enim error adipisci nisi.', 'https://via.placeholder.com/640x480.png/002255?text=films+dolores', 'HK', 'Park Chan-Wook', '21:46:14', 'Focus Features', 'Documentary', 'Charlize Theron'),
(208, 'Rear Window', '3', 'The cook threw a frying-pan after her as she left her, leaning her head in the sun. (IF you don\'t know what \"it\" means well enough, when I was sent for.\' \'You ought to go near the King said, turning to the Knave of Hearts, she made it out again, and Alice', 'Aut eum nobis sapiente omnis id. Quam facere qui dolores commodi aut ut maiores. Eveniet dolorem aliquid dolorem. Ut eveniet aliquam id.', 'https://via.placeholder.com/640x480.png/008833?text=films+qui', 'BQ', 'John Ford', '20:53:38', 'Bad Robot', 'TV Movie', 'Forest Whitaker'),
(209, 'La La Land', '8', 'Dinah my dear! Let this be a grin, and she went round the thistle again; then the Mock Turtle, \'but if you\'ve seen them so often, of course had to kneel down on her spectacles, and began to say to itself in a voice of the evening, beautiful Soup! Soup of ', 'Molestias molestias ullam sunt ducimus delectus corrupti. Dolor itaque non ullam eum. Sint unde omnis ullam quasi voluptate. Harum possimus rerum unde perferendis qui sunt. Ratione maxime itaque et rem fugit voluptate ullam. Expedita rerum consequatur qui', 'https://via.placeholder.com/640x480.png/00aa22?text=films+pariatur', 'TZ', 'Lana Wachowski', '18:17:37', 'Dreamworks', 'Western', 'Jonah Hill'),
(210, '12 Angry Men', '4', 'Hatter was the Cat in a great hurry. An enormous puppy was looking at it again: but he could think of what work it would like the Queen?\' said the Mock Turtle repeated thoughtfully. \'I should like to hear her try and say \"How doth the little--\"\' and she w', 'Quis iste porro maxime impedit commodi est. Officiis et maxime dignissimos voluptas sint quo. Dolores reprehenderit quos pariatur sed atque ipsam quia.', 'https://via.placeholder.com/640x480.png/003311?text=films+pariatur', 'AT', 'George Lucas', '19:53:51', 'Paramount', 'Documentary', 'Al Pacino'),
(211, 'Signs', '9', 'Alice, \'shall I NEVER get any older than I am to see the Hatter said, tossing his head contemptuously. \'I dare say you\'re wondering why I don\'t know where Dinn may be,\' said the Dodo, pointing to the voice of the words have got in your pocket?\' he went on', 'Nostrum cumque deserunt aliquid. Inventore quidem quo quia ducimus ut modi. Aut minus distinctio magni asperiores nemo at corporis. Qui officiis provident et exercitationem et.', 'https://via.placeholder.com/640x480.png/00cc33?text=films+laboriosam', 'CD', 'Claire Denis', '23:03:01', 'Focus Features', 'History', 'Jake Gyllenhaal'),
(212, 'V for Vendetta', '6', 'Alice did not notice this last remark that had fallen into the earth. Let me see: four times five is twelve, and four times five is twelve, and four times five is twelve, and four times seven is--oh dear! I shall see it trot away quietly into the air. Eve', 'Praesentium eos delectus quibusdam rerum. Similique sed eum eius inventore perspiciatis. Perspiciatis rerum molestiae sapiente est nesciunt distinctio est. Unde et molestiae non ipsam placeat et. Voluptatem nulla perspiciatis cupiditate sit laudantium con', 'https://via.placeholder.com/640x480.png/00bb33?text=films+aperiam', 'TW', 'Chloé Zhao', '22:10:26', 'Bad Robot', 'Animation', 'Ralph Fiennes'),
(213, 'No Country for Old Men', '5', 'Duchess: \'and the moral of THAT is--\"Take care of themselves.\"\' \'How fond she is of yours.\"\' \'Oh, I know!\' exclaimed Alice, who was passing at the stick, and held out its arms and legs in all directions, \'just like a tunnel for some time without interrupt', 'Aspernatur eos sunt et consectetur. Adipisci aut quam voluptatem cumque itaque enim. Id saepe quidem labore aut est. Veritatis provident quaerat modi aspernatur quo consequuntur laborum.', 'https://via.placeholder.com/640x480.png/005511?text=films+adipisci', 'KE', 'Danny Boyle', '23:49:10', 'Gaumont', 'History', 'Al Pacino'),
(214, 'Spotlight', '7', 'Only I don\'t like them raw.\' \'Well, be off, and that is enough,\' Said his father; \'don\'t give yourself airs! Do you think you can find it.\' And she went on \'And how did you call it purring, not growling,\' said Alice. \'I wonder what Latitude was, or Longit', 'Sint doloribus recusandae aperiam sunt cumque deleniti. Quia alias qui sint ea pariatur et eius. Voluptatem sed et aut totam illo ut perspiciatis itaque. Aut minus consequatur sint architecto.', 'https://via.placeholder.com/640x480.png/00ee99?text=films+consequatur', 'MU', 'James Wan', '18:47:33', 'The Asylum', 'Thriller', 'Nicole Kidman'),
(215, 'Andreï Roublev', '5', 'And yet I don\'t take this child away with me,\' thought Alice, and, after folding his arms and frowning at the cook, and a large dish of tarts upon it: they looked so good, that it seemed quite natural); but when the tide rises and sharks are around, His v', 'Impedit similique sit repellat aspernatur iusto beatae. Illum et et ipsam exercitationem assumenda est. Provident labore rem quidem quasi. Officia reiciendis beatae cupiditate sunt nesciunt quia sit. Excepturi sunt qui perferendis vel.', 'https://via.placeholder.com/640x480.png/000022?text=films+cumque', 'CF', 'Danny Boyle', '19:18:14', 'Regency', 'History', 'Shailene Woodley'),
(216, '12 Angry Men', '4', 'Queen was silent. The King laid his hand upon her face. \'Very,\' said Alice: \'--where\'s the Duchess?\' \'Hush! Hush!\' said the King, the Queen, but she stopped hastily, for the immediate adoption of more broken glass.) \'Now tell me, Pat, what\'s that in some ', 'Quia provident esse rerum. A excepturi optio temporibus molestiae. Voluptate enim quos temporibus. Et voluptas dolore molestias non quia. Maiores eum suscipit non exercitationem beatae. Eos quasi et asperiores sed est. Molestiae et modi consequatur atque ', 'https://via.placeholder.com/640x480.png/0077dd?text=films+exercitationem', 'SV', 'Sam Mendes', '22:25:56', 'A24', 'Thriller', 'Brad Pitt'),
(217, 'Arrival', '6', 'Mouse to tell them something more. \'You promised to tell me who YOU are, first.\' \'Why?\' said the Hatter. He came in with the other: the Duchess sang the second time round, she found it so quickly that the pebbles were all talking at once, in a very curiou', 'Sed cumque omnis numquam doloribus ut et. Et vel recusandae ut vitae id error porro. Voluptatibus repudiandae rerum veritatis rerum sequi pariatur sed. Quae consequuntur consequatur aut dolorem et deserunt. Corporis quibusdam commodi et repudiandae explic', 'https://via.placeholder.com/640x480.png/0011dd?text=films+ut', 'TZ', 'Clint Eastwood', '18:21:57', 'Syncopy', 'History', 'Jennifer Lawrence'),
(218, 'The Grand Budapest Hotel', '8', 'Hatter, and here the Mock Turtle, capering wildly about. \'Change lobsters again!\' yelled the Gryphon went on at last, with a knife, it usually bleeds; and she walked sadly down the chimney!\' \'Oh! So Bill\'s got to go among mad people,\' Alice remarked. \'Rig', 'Quae nesciunt alias repellat dolores est sed. Sint voluptates blanditiis voluptate consequatur eaque excepturi aut. Cupiditate quaerat non quam ex eos. Nobis sit veniam nam quo consequuntur ducimus illum quas.', 'https://via.placeholder.com/640x480.png/007744?text=films+ea', 'PR', 'Nancy Meyers', '22:17:48', 'Lucasfilm', 'Horror', 'Emma Stone'),
(219, 'The Thing', '7', 'Dormouse went on, \'if you don\'t like them!\' When the pie was all finished, the Owl, as a last resource, she put them into a large pool all round the thistle again; then the puppy began a series of short charges at the top of his head. But at any rate: go ', 'Ducimus rerum culpa nihil qui tempora dolore. Fugiat nesciunt non dolorem voluptas autem. Veniam enim officiis non voluptatum. Labore rerum rerum quis. Sequi explicabo alias tempore unde laudantium sed. Illo quod ut hic ut libero neque aut. Hic qui cumque', 'https://via.placeholder.com/640x480.png/009966?text=films+itaque', 'LC', 'Ethan Coen', '23:45:01', '20th Century Fox', 'Science Fiction', 'Gene Hackman'),
(220, 'The Dark Knight', '3', 'As a duck with its mouth and began talking again. \'Dinah\'ll miss me very much what would be a LITTLE larger, sir, if you please! \"William the Conqueror, whose cause was favoured by the pope, was soon submitted to by the Queen said--\' \'Get to your tea; it\'', 'Eius dolore sit voluptatibus aspernatur quo. Sint ad aspernatur magni aut. Ipsam pariatur eius error vero illum. Unde quae aliquam praesentium voluptates dicta architecto.', 'https://via.placeholder.com/640x480.png/009900?text=films+impedit', 'JP', 'Lynne Ramsay', '20:34:32', '20th Century Fox', 'TV Movie', 'Catherine Deneuve'),
(221, 'Persona', '3', 'There was nothing else to do, and perhaps after all it might appear to others that what you had been looking over his shoulder with some severity; \'it\'s very interesting. I never knew whether it was out of court! Suppress him! Pinch him! Off with his whis', 'Asperiores eius officiis sit eum amet. Ipsam deserunt voluptates autem dolorem. Nesciunt et aliquam adipisci qui id sapiente repellendus. Sit aut modi provident aut. Eius voluptatum aut sunt aut est corporis eius. Repudiandae eum et nihil non. Et consequa', 'https://via.placeholder.com/640x480.png/00bb88?text=films+hic', 'GA', 'Kelly Reichardt', '22:01:01', 'Legendary Pictures', 'Biography', 'Jonah Hill'),
(222, 'Rosemary\'s Baby', '5', 'Alice the moment how large she had known them all her wonderful Adventures, till she fancied she heard one of the Mock Turtle, suddenly dropping his voice; and Alice was a large crowd collected round it: there were TWO little shrieks, and more sounds of b', 'Sapiente officia consequuntur repudiandae harum dolore tenetur asperiores possimus. Sint odio enim ut porro illum blanditiis ullam. Repudiandae sequi magni sunt.', 'https://via.placeholder.com/640x480.png/0055ee?text=films+libero', 'RO', 'David Lynch', '18:27:38', 'Legendary Pictures', 'Action', 'Woody Allen'),
(223, 'Eyes Wide Shut', '5', 'And argued each case with MINE,\' said the Mock Turtle had just succeeded in curving it down into its face to see how he did it,) he did with the Dormouse. \'Write that down,\' the King put on his slate with one of the tea--\' \'The twinkling of the lefthand b', 'Sit ducimus itaque alias odit voluptas. Quasi qui sapiente quisquam saepe ut. Corrupti ut dolores sequi laborum dolores qui. Dicta nemo a voluptates dicta adipisci blanditiis ducimus repudiandae. Repellat est cumque praesentium nihil est iure fugit quidem', 'https://via.placeholder.com/640x480.png/00bbee?text=films+nisi', 'BR', 'Barbra Streisand', '19:52:39', 'The Asylum', 'Crime', 'Diane Keaton'),
(224, 'Inception', '9', 'He got behind him, and said \'What else have you executed on the Duchess\'s knee, while plates and dishes crashed around it--once more the shriek of the jurors had a large dish of tarts upon it: they looked so grave and anxious.) Alice could hear the very t', 'Repellat esse doloremque explicabo in cumque doloremque eum. Exercitationem doloribus quos ad. Harum quis optio rem. Quisquam enim provident veritatis eum natus optio dolore.', 'https://via.placeholder.com/640x480.png/00dd88?text=films+nobis', 'GW', 'David O.Russel', '21:56:49', 'Amblin', 'Western', 'Kevin Spacey'),
(225, 'Green Book', '6', 'The Mock Turtle at last, with a sigh: \'he taught Laughing and Grief, they used to know. Let me think: was I the same words as before, \'and things are worse than ever,\' thought the whole court was a treacle-well.\' \'There\'s no sort of circle, (\'the exact sh', 'Neque eum molestiae expedita numquam quae. Placeat aut quis et magnam. Voluptas qui voluptatem totam velit sint consectetur accusamus. Non iste repellendus deserunt et voluptatem voluptatem aut. Omnis explicabo aperiam reiciendis incidunt ut sint quia. Es', 'https://via.placeholder.com/640x480.png/0022ff?text=films+aut', 'ET', 'Luis Buñuel', '21:09:43', 'Bad Robot', 'Science Fiction', 'Michael Douglas'),
(226, 'Polytechnique', '7', 'French lesson-book. The Mouse gave a look askance-- Said he thanked the whiting kindly, but he could think of any one; so, when the race was over. Alice was just beginning to see if he doesn\'t begin.\' But she waited patiently. \'Once,\' said the Duck. \'Foun', 'Nulla accusantium illo et aut. Expedita assumenda nemo est consequuntur. Et vero et nisi explicabo tempore illo. Porro sed et enim autem adipisci. Explicabo eaque et est nihil harum. Quae quo sit et sequi accusantium quisquam magnam.', 'https://via.placeholder.com/640x480.png/0066dd?text=films+quia', 'DJ', 'Marguerite Duras', '22:47:27', 'Fox Searchlight Pictures', 'TV Movie', 'Marlene Dietrich'),
(227, 'Rear Window', '4', 'Alice did not dare to disobey, though she looked down at her hands, and began:-- \'You are old,\' said the Gryphon. \'They can\'t have anything to say, she simply bowed, and took the least idea what to say \'creatures,\' you see, because some of the country is,', 'Incidunt deserunt ex voluptate sapiente voluptas et. Ea incidunt veniam deserunt et. Non ab et eos voluptas ad eius. Expedita dolorem rerum facilis fuga voluptatem provident.', 'https://via.placeholder.com/640x480.png/003300?text=films+deserunt', 'CI', 'Sam Mendes', '22:28:38', 'Universal Pictures', 'Action', 'Alicia Vikander'),
(228, 'Alien', '7', 'ARE you talking to?\' said the Mock Turtle. \'She can\'t explain MYSELF, I\'m afraid, sir\' said Alice, and looking at Alice for some while in silence. Alice noticed with some curiosity. \'What a pity it wouldn\'t stay!\' sighed the Lory, with a kind of authority', 'Reprehenderit sint alias tenetur non mollitia dolores rem. Aut et ut iusto eveniet voluptatem fugiat. Dolor inventore blanditiis facere dignissimos quia iure. Ut temporibus ut earum. Quia ullam distinctio sit qui harum molestiae. Quas possimus voluptas do', 'https://via.placeholder.com/640x480.png/00bb55?text=films+consequuntur', 'SK', 'Ridley Scott', '18:06:40', 'Studio Canal', 'Romance', 'Annie Girardot'),
(229, 'Gone Girl', '9', 'The King turned pale, and shut his eyes.--\'Tell her about the right thing to get very tired of sitting by her sister on the end of his tail. \'As if I must, I must,\' the King exclaimed, turning to Alice as it went, as if it makes me grow larger, I can list', 'Aut omnis ut nemo voluptas deleniti consequatur tenetur. Repellendus nesciunt corporis consectetur quo est vitae. Fugiat et aut cupiditate. Nam nesciunt exercitationem non et voluptatibus animi laborum. Quae quasi molestiae autem ipsum minima quisquam aut', 'https://via.placeholder.com/640x480.png/00cc22?text=films+vitae', 'CI', 'Jim Jarmush', '22:36:41', 'Universal Pictures', 'Suspense', 'Juliane Moore'),
(230, 'A Beautiful Mind', '5', 'Queen\'s ears--\' the Rabbit came up to her feet, they seemed to Alice an excellent opportunity for repeating his remark, with variations. \'I shall be punished for it to his ear. Alice considered a little recovered from the shock of being all alone here!\' A', 'Quia aut magnam vitae. Deleniti culpa delectus dicta quo facilis et beatae. Dolorem repudiandae assumenda voluptas quo exercitationem. Esse repudiandae ut explicabo eum. Et eum at rerum ipsam aut ab. Consequatur nostrum tempore repellat. Asperiores illum ', 'https://via.placeholder.com/640x480.png/003377?text=films+labore', 'AR', 'George Miller', '23:30:38', 'UGC', 'Crime', 'Kevin Spacey'),
(231, 'The Handmaiden', '2', 'I\'ve kept her eyes to see if there are, nobody attends to them--and you\'ve no idea what Latitude or Longitude either, but thought they were playing the Queen was to twist it up into the sea, \'and in that soup!\' Alice said very humbly; \'I won\'t indeed!\' sa', 'Qui qui alias rem dolor eos et voluptas. Repellat vero enim ullam reprehenderit doloremque enim maiores. Et ab mollitia beatae nesciunt porro vero eum. Et ut autem quidem optio aspernatur recusandae et.', 'https://via.placeholder.com/640x480.png/00ffff?text=films+praesentium', 'PT', 'Greta Gerwig', '18:41:09', 'New Line Cinema', 'Western', 'Ralph Fiennes'),
(232, 'Jaws', '7', 'Mock Turtle. \'No, no! The adventures first,\' said the Hatter. He came in sight of the tale was something like it,\' said Alice indignantly, and she ran off at once, in a moment. \'Let\'s go on crying in this affair, He trusts to you to set about it; if I\'m M', 'Eos vero perspiciatis ut reiciendis et. Ipsum iusto ut aut dicta qui molestiae. Corrupti excepturi necessitatibus eveniet et qui rem. In accusantium nisi qui.', 'https://via.placeholder.com/640x480.png/001177?text=films+sit', 'MT', 'Ethan Coen', '23:34:43', 'A Band Apart', 'Suspense', 'Michael Shannon'),
(233, 'Once Upon a Time in the West', '6', 'Alice, very earnestly. \'I\'ve had nothing yet,\' Alice replied in an agony of terror. \'Oh, there goes his PRECIOUS nose\'; as an unusually large saucepan flew close by her. There was a general chorus of \'There goes Bill!\' then the puppy jumped into the garde', 'Amet omnis at ut consectetur. Voluptatem consequatur velit accusantium debitis. Suscipit qui ipsum nesciunt maiores qui impedit dolorem. Inventore possimus ad corrupti iusto maiores aspernatur.', 'https://via.placeholder.com/640x480.png/001199?text=films+veniam', 'ZM', 'Gaspar Noé', '20:31:37', 'UGC', 'Drama', 'Christopher Walken'),
(234, 'L.A. Confidential', '3', 'Mary Ann, what ARE you talking to?\' said one of them attempted to explain the paper. \'If there\'s no harm in trying.\' So she began very cautiously: \'But I don\'t think,\' Alice went on, turning to Alice, she went on in a sulky tone, as it could go, and makin', 'Aperiam voluptatum odit quia alias sint sint consectetur. Illo praesentium omnis molestiae consequatur nulla delectus. Labore esse ipsum id dolores voluptatem libero dolorem numquam. Ut ducimus doloremque excepturi quis.', 'https://via.placeholder.com/640x480.png/008888?text=films+modi', 'GQ', 'Quentin Tarantino', '23:34:39', 'Walt Disney Studios', 'Western', 'Ingrid Bergman'),
(235, 'Blow Out', '2', 'So she began: \'O Mouse, do you mean \"purpose\"?\' said Alice. \'Why not?\' said the Queen, in a great deal to ME,\' said Alice timidly. \'Would you tell me,\' said Alice, in a piteous tone. And she tried the little door, so she helped herself to about two feet h', 'Fuga quisquam dignissimos et dolorem ut. Reprehenderit illo distinctio exercitationem non esse iusto possimus. Ut suscipit aut hic recusandae. Sint expedita laborum et repellat. Animi possimus sunt alias impedit soluta. Id optio error perferendis molestia', 'https://via.placeholder.com/640x480.png/0000cc?text=films+non', 'IS', 'Joel Coen', '20:58:50', 'Sony PictureS', 'Music', 'Jeff Bridges'),
(236, 'Life is beautiful', '1', 'Gryphon hastily. \'Go on with the bread-and-butter getting so far off). \'Oh, my poor little thing was snorting like a wild beast, screamed \'Off with her head!\' about once in the window, she suddenly spread out her hand, watching the setting sun, and thinki', 'Qui inventore rem ea modi est. Voluptas fugiat saepe est enim deleniti minima illum. Expedita suscipit dolor voluptates eos. Ipsa culpa quo doloribus aliquid. Nesciunt aspernatur enim optio distinctio eum ea.', 'https://via.placeholder.com/640x480.png/0066aa?text=films+sed', 'MC', 'Damien Chazelle', '21:47:42', 'Gaumont', 'Drama', 'Carey Mulligan'),
(237, 'Finding Nemo', '5', 'This time there were any tears. No, there were no arches left, and all her knowledge of history, Alice had no pictures or conversations?\' So she stood still where she was, and waited. When the pie was all ridges and furrows; the balls were live.', 'Sapiente possimus qui minus velit aliquid. Voluptas architecto iusto repellendus dolor dolorem corrupti omnis est. Cupiditate culpa tempore qui eum unde voluptas.', 'https://via.placeholder.com/640x480.png/00ccdd?text=films+voluptate', 'GY', 'Ridley Scott', '18:14:41', 'Miramax Films', 'Documentary', 'Bryan Cranston'),
(238, 'Back to the Future 2', '1', 'Alice, swallowing down her anger as well go back, and barking hoarsely all the jurymen are back in their mouths; and the executioner went off like an honest man.\' There was a large kitchen, which was the BEST butter, you know.\' He was an uncomfortably sha', 'Et non possimus modi perferendis sapiente cumque. Odio consequatur sapiente consectetur omnis. Velit dolorum nihil consequatur consequatur. Quo delectus autem voluptatem qui voluptatum autem.', 'https://via.placeholder.com/640x480.png/0011aa?text=films+hic', 'VU', 'George Miller', '19:48:23', 'Marvel Studios', 'Thriller', 'Anna Kendrick'),
(239, 'Gravity', '9', 'March Hare: she thought at first was moderate. But the insolence of his tail. \'As if I chose,\' the Duchess and the reason and all must have been changed in the middle, being held up by a row of lodging houses, and behind them a railway station.) However, ', 'Explicabo qui aut qui. Quo distinctio consectetur qui voluptas et alias itaque similique. Ut autem asperiores et saepe reprehenderit dolorem.', 'https://via.placeholder.com/640x480.png/009944?text=films+laborum', 'OM', 'Lynne Ramsay', '21:17:57', 'Fox Searchlight Pictures', 'Family', 'Juliane Moore'),
(240, 'Trainspotting', '8', 'Dormouse. \'Don\'t talk nonsense,\' said Alice to herself. Imagine her surprise, when the Rabbit came up to her usual height. It was opened by another footman in livery, with a shiver. \'I beg your pardon!\' cried Alice (she was so much contradicted in her Fre', 'Praesentium cumque dolorem debitis odit deleniti. Laudantium perferendis qui architecto quo aliquid rerum. Eos illum reiciendis dignissimos voluptas. Consequatur corporis maiores deserunt. Omnis dicta necessitatibus sit quia ea.', 'https://via.placeholder.com/640x480.png/001144?text=films+aut', 'CM', 'Bong Joon-ho', '19:20:23', 'Sony PictureS', 'TV Movie', 'Ralph Fiennes'),
(241, 'There Will Be Blood', '9', 'She did it at all,\' said Alice: \'besides, that\'s not a VERY turn-up nose, much more like a tunnel for some minutes. Alice thought decidedly uncivil. \'But perhaps it was very likely to eat or drink anything; so I\'ll just see what the moral of that is--\"Oh,', 'Dolorem voluptatem placeat asperiores vel quo ab. Dicta et voluptatum dolores. Illum asperiores et laudantium at in adipisci. Incidunt ea facilis adipisci officiis ut. Beatae est porro rerum perferendis. Accusamus vero rerum ut doloremque ut nemo eum. Del', 'https://via.placeholder.com/640x480.png/0066aa?text=films+dolor', 'VA', 'Pedro Almodovar', '23:16:19', 'Gaumont', 'Thriller', 'Sharon Stone'),
(242, 'Memories of Murder', '2', 'I should understand that better,\' Alice said nothing: she had quite forgotten the Duchess was sitting on the ground as she had finished, her sister on the same thing as a boon, Was kindly permitted to pocket the spoon: While the Owl and the baby joined):-', 'Sunt repellendus aperiam dignissimos eum dolore. Quam blanditiis quia sed aut qui quae ab. Vero sapiente dolores molestiae tempore qui. Deserunt eveniet quis dignissimos eveniet animi rerum veniam cum.', 'https://via.placeholder.com/640x480.png/007722?text=films+sequi', 'LC', 'Alain Resnais', '19:12:10', 'Focus Features', 'Biography', 'Steve Carell'),
(243, '12 Years a Slave', '5', 'I think.\' And she squeezed herself up and bawled out, \"He\'s murdering the time! Off with his head!\' she said, without even waiting to put down yet, before the trial\'s begun.\' \'They\'re putting down their names,\' the Gryphon repeated impatiently: \'it begins', 'Dolores blanditiis nostrum ipsa dolorem ut. Et est veniam unde saepe nam ut incidunt et. Dolorum omnis id aut sit hic et a vel. Error placeat tempore qui quis porro consequatur. Quidem eum et quia voluptates ea. Temporibus et animi libero est id soluta re', 'https://via.placeholder.com/640x480.png/004477?text=films+adipisci', 'US', 'JJ Abrams', '20:43:26', 'Columbia Pictures', 'War', 'Ana de Armas'),
(244, 'The Green Mile', '3', 'Queen to play with, and oh! ever so many tea-things are put out here?\' she asked. \'Yes, that\'s it,\' said the Dodo, pointing to the heads of the bread-and-butter. Just at this moment the King, with an M, such as mouse-traps, and the reason of that?\' \'In my', 'Alias sed ea sunt hic dolores quisquam. Officia iure rerum consectetur officiis. Assumenda iusto harum rem pariatur. Aut qui non quis qui error.', 'https://via.placeholder.com/640x480.png/006699?text=films+sed', 'SC', 'Andrea Arnold', '22:48:26', 'Sony PictureS', 'Drama', 'Paul Dano'),
(245, 'Interstellar', '7', 'I to get an opportunity of showing off a bit afraid of it. She went on talking: \'Dear, dear! How queer everything is to-day! And yesterday things went on \'And how many miles I\'ve fallen by this time). \'Don\'t grunt,\' said Alice; \'that\'s not at all what had', 'Omnis ea veniam quibusdam cum sit maxime et deleniti. Ducimus assumenda animi tempora et rem. Quia atque quos velit quis corporis labore illum. Temporibus sed voluptatum dolor vel deserunt. Ea consequatur eveniet eius. Quasi nemo cum dicta velit soluta su', 'https://via.placeholder.com/640x480.png/000022?text=films+dolores', 'AG', 'Paul Greengrass', '23:53:03', 'New Line Cinema', 'Fantasy', 'Kenneth Branagh'),
(246, 'The Big Lebowski', '6', 'Gryphon. \'It all came different!\' Alice replied in an undertone to the seaside once in her hands, and was coming to, but it had been. But her sister kissed her, and said, \'So you did, old fellow!\' said the Mouse had changed his mind, and was delighted to ', 'Perspiciatis mollitia nostrum aperiam. Ullam saepe dolorem sit facere et. Earum vel vero excepturi. Aliquam nam odit voluptas nulla aperiam eos tempore.', 'https://via.placeholder.com/640x480.png/00cc77?text=films+perspiciatis', 'US', 'Michael Bay', '20:43:47', 'Universal Pictures', 'Animation', 'Jonah Hill'),
(247, 'The Big Lebowski', '2', 'Pat, what\'s that in about half no time! Take your choice!\' The Duchess took her choice, and was looking up into a small passage, not much surprised at this, but at last in the grass, merely remarking that a moment\'s delay would cost them their lives. All ', 'Ipsa et totam delectus in ipsam. Blanditiis nemo ut molestiae voluptatem vero. Adipisci molestiae eos ducimus sed.', 'https://via.placeholder.com/640x480.png/002211?text=films+aut', 'NP', 'Jean Renoir', '22:18:53', 'TriStar', 'Drama', 'Nicole Kidman'),
(248, 'Back to the Future 2', '8', 'CAN I have none, Why, I haven\'t been invited yet.\' \'You\'ll see me there,\' said the Footman, and began to feel a little bit of stick, and tumbled head over heels in its hurry to change the subject. \'Ten hours the first minute or two, she made out that the ', 'Molestiae natus et odit quos. Rem libero eius sunt fugit. Ipsum assumenda nostrum est sed ut facere. Non rerum consequatur ut.', 'https://via.placeholder.com/640x480.png/001100?text=films+quia', 'SR', 'Dario Argento', '21:57:12', 'A Band Apart', 'Mystery', 'Rosamund Pike'),
(249, 'No Country for Old Men', '9', 'I\'ll manage better this time,\' she said, without even waiting to put his mouth close to her, \'if we had the best cat in the schoolroom, and though this was the White Rabbit, \'but it seems to grin, How neatly spread his claws, And welcome little fishes in ', 'Qui blanditiis et cumque explicabo velit enim itaque. Occaecati nemo fugit voluptatem inventore dolorem. Quasi quasi quasi et neque deserunt vero dicta non. Corporis aut inventore ipsam omnis suscipit. Nemo non quae velit occaecati et id nesciunt est. Nis', 'https://via.placeholder.com/640x480.png/00bb55?text=films+dolor', 'RS', 'Jacques Audiard', '20:31:27', 'A24', 'Adventure', 'Joe Pesci'),
(250, 'Reservoir Dogs', '2', 'Alice ventured to remark. \'Tut, tut, child!\' said the King; \'and don\'t look at the beginning,\' the King eagerly, and he called the Queen, turning purple. \'I won\'t!\' said Alice. \'I mean what I say,\' the Mock Turtle went on. \'I do,\' Alice said to herself; \'', 'Autem omnis consequuntur fugiat neque. Laborum dicta quasi libero voluptatem est. Explicabo voluptatibus quisquam dolore fugit ab odio ut.', 'https://via.placeholder.com/640x480.png/00dd66?text=films+quod', 'VG', 'Steve McQueen', '19:12:06', 'New Line Cinema', 'History', 'Ellen Page'),
(251, 'City of God', '1', 'Five! Always lay the blame on others!\' \'YOU\'D better not do that again!\' which produced another dead silence. \'It\'s a pun!\' the King said, with a smile. There was a body to cut it off from: that he shook his grey locks, \'I kept all my life, never!\' They h', 'Totam accusamus voluptate maxime animi et aut quis. Omnis repellat voluptatum autem quo sunt in placeat. Officiis accusamus quia nesciunt illum. Non consequatur id ut ut illum iste.', 'https://via.placeholder.com/640x480.png/00ccdd?text=films+ipsa', 'DK', 'Francois Truffaut', '22:37:11', 'Columbia Pictures', 'Adventure', 'Emma Watson'),
(252, 'Panic Room', '4', 'Dormouse went on, \'you see, a dog growls when it\'s angry, and wags its tail when I\'m angry. Therefore I\'m mad.\' \'I call it sad?\' And she began again: \'Ou est ma chatte?\' which was full of the way to change the subject. \'Ten hours the first position in dan', 'Voluptas repudiandae qui consequuntur voluptas nemo. Est pariatur a beatae nihil in quae. Corrupti numquam nostrum aut. Velit aliquam nulla consequatur ipsa quis. Id maxime delectus architecto nesciunt distinctio. Sit odio eos officiis sed maxime eum aute', 'https://via.placeholder.com/640x480.png/00cc55?text=films+qui', 'CU', 'Marry Harron', '23:15:48', 'New Line Cinema', 'Drama', 'Ellen Page'),
(253, 'A bout de souffle', '1', 'Duck and a large one, but the three gardeners instantly threw themselves flat upon their faces. There was a very interesting dance to watch,\' said Alice, who felt very curious to see you any more!\' And here Alice began to repeat it, when a cry of \'The tri', 'Id quis odio sit qui earum cumque repellat. Dolorem optio ut ut sed voluptatem similique. Ea consequuntur error sed perspiciatis. Voluptas facere a eos nesciunt libero pariatur ad. Natus quos quibusdam eos alias porro deleniti. Nam dolorum tenetur facere ', 'https://via.placeholder.com/640x480.png/0033aa?text=films+nemo', 'SK', 'Charles Chaplin', '19:04:00', 'Warner Bros', 'Documentary', 'Christian Bale'),
(254, 'Logan', '6', 'And beat him when he finds out who I am! But I\'d better take him his fan and two or three pairs of tiny white kid gloves, and was going to happen next. \'It\'s--it\'s a very decided tone: \'tell her something about the games now.\' CHAPTER X. The Lobster Quadr', 'Qui assumenda veniam ut quis nemo. Reprehenderit sed velit distinctio. Adipisci animi culpa sunt ipsa. Asperiores quis non explicabo occaecati deleniti. Ab magnam ipsa voluptatum molestias hic in. Voluptas doloremque labore distinctio magnam voluptas libe', 'https://via.placeholder.com/640x480.png/00bb99?text=films+est', 'YE', 'François Ozon', '23:00:11', 'Universal Pictures', 'TV Movie', 'Kate Winslet'),
(255, 'Your Name', '5', 'They all sat down at her side. She was a good thing!\' she said to herself, \'it would have this cat removed!\' The Queen turned crimson with fury, and, after folding his arms and legs in all directions, \'just like a star-fish,\' thought Alice. The poor littl', 'Mollitia quia ab sunt optio excepturi. Molestiae vel voluptas ad vero dolores non. Reiciendis fuga dolorem animi ex deserunt quod.', 'https://via.placeholder.com/640x480.png/0044dd?text=films+eaque', 'MW', 'Francois Truffaut', '22:19:39', 'Lucasfilm', 'Biography', 'Leonardo DiCaprio'),
(256, 'Trainspotting', '5', 'Cat. \'Do you mean by that?\' said the sage, as he spoke, and added with a sigh. \'I only took the watch and looked at them with large eyes like a tunnel for some time with one finger pressed upon its forehead (the position in dancing.\' Alice said; \'there\'s ', 'Officia necessitatibus dolore consequatur qui tenetur. Explicabo est in repellendus voluptatum. Consequatur nesciunt numquam veniam. Vel placeat dolor et deserunt. Sunt beatae dicta similique nesciunt autem. Est rerum suscipit laborum pariatur repellat ut', 'https://via.placeholder.com/640x480.png/00aa88?text=films+atque', 'NU', 'Richard Linklater', '23:20:37', 'Marvel Studios', 'Thriller', 'Viola Davis');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `film`
--
ALTER TABLE `film`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `film`
--
ALTER TABLE `film`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=257;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
